AllCops:
  TargetRubyVersion: 2.2
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Documentation:
  Enabled: false
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/MethodLength:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 25
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'
Naming/UncommunicativeMethodParamName:
  MinNameLength: 0
Naming/FileName:
  Exclude:
    - 'lib/sheep-a-changelog.rb'
    - 'spec/sheep-a-changelog_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/ClassVars:
  Exclude:
    - 'spec/**/*.rb'