AllCops:
  TargetRubyVersion: 2.2
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Documentation:
  Enabled: false
Layout/IndentArray:
  EnforcedStyle: consistent
Metrics/LineLength:
  Exclude:
    - 'spec/**/*.rb'
Naming/UncommunicativeMethodParamName:
  MinNameLength: 0
Naming/FileName:
  Exclude:
    - 'lib/sheep-a-changelog.rb'
    - 'spec/sheep-a-changelog_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Style/ClassVars:
  Exclude:
    - 'spec/**/*.rb'