language: ruby
rvm:
- 2.2
- 2.3
- 2.4
- 2.5
script:
- bundle exec rake test
- bundle exec rake cs
deploy:
  provider: rubygems
  api_key:
    secure: ytiJYXH2mRPdkguBdK+oT4Np4K89SxprbVWgCZtgsledSTLii4Itf3PAeH09gt7PQJI7QKxY/uJafz1G8VtBZrkVAUvuypFRh2ylHcfM0jhjqn4wzTlTNNZhkJl5OIePZFjTKufrtwI1SRzKUicjz7jdAhEorH5ENDsGtq2MA4pTtlDGShJxwFJEKOFc1/vHzjaXRYiMFiAv5jvauolJAMn3Zsf/PCXv8pM9aazbsL3UniqGTOBdpoqnEYpsjCxwiZY6GJGguAuqA30vX/yGSR1zmsX8Tu+CS97WGQRQt4tXr1wQ2PE7RrgKzww4kxA4eGDBvWacyXPmDBy4nG9sV7REP2DTumQCUbuENbfwGBftp5CxqRVvI0CSND+wsVRNZbo6Jahm4TontYGSX+zqymi50NQqNlw063ObTN4R1qDoK1DVMMTFyIZd3sUC5gjOvpCu8od8qMQGJI3vCymrB6XE8iCs8qaq8aK+bPEUnh/PakM5v+tekRBZZpVHzM0Mcy0xvUZ6Q8RPs817q16Lj7iFC8KfnkR7zYttuTmxv+ZHguu4Do6RokW9u9HC/Nsjm9KfFkOAZ4RKKXlaJGahpggldWi7OV/To9/QTvZSske72jRgVs3AzAZvAuAzX0+jnVmXDxi0EoHF0UyE9IAC7h/7nbneXfX3X8wSbLl6xLs=
  gem: sheep-a-changelog
  on:
    tags: true
    repo: grissius/sheep-a-changelog
