language: ruby
rvm:
- 2.2
- 2.3
- 2.4
- 2.5
script:
- bundle exec rake test
- bundle exec rake cs
deploy:
  provider: rubygems
  api_key:
    secure: e/MJiLV1DrvvxI7Q68jn34BhfCBWlLsiM7JTnN7619C1bO0I5rL7WKOBIXezVlzoMKOr2FAgEmMi6s3DyrqUWEz893u9tOtIUe1zW8xiQnXBP3HcCt/JcPoF77a5v7sCfhmgAr87EXgIlQ1cd9MkmO/AwxQ0b3IkcHT4ve5F+eeK52BTfACDF8UoF3xI/+TdRNodE6a2vR0KL8T6MPE6lXjyUNBJFA3y7f6wkBX35Teg8tWzv5zxmhZXLykn6pynkgWY1TRzQAHViX21QKNy1B0JW5YSkpCuFVdpbk7BX24nbf/zJTdvX5vajVtPE1x7ejcWLRSDMOFdeARAeh0EGPtFa6AMO+M76fEhxSkV8jXHeEW3tAuWcgTzRvVpYdKj0WXM9W82aIpvQM8mJxfSR+lF4O9l/AHtUoe4RhKsS/UKTBArnwXv0QHjyTbiYg2jHsOQ0/vtFteZd68NxOVyFBeJUgk8SFXMePCL/M9SYHErYrR4IRYlGu1tqU+VZw+NR/7T3USwwH4408ws0rnWX+khEfJeWWrOVOsytTil+FYARNxRZnGaeMm/hki9+gRPACejAxN9EaMYp/oUNhRb3uxoKpMy0eYQJe/TqYjxTbLF32w9WXbE1zfWUWgGRJvmhSTfAebACHIsW1GOmCnQL5KNwB5I4vsOLBpbcOTfEu8=
  gem: sheep-a-changelog
  on:
    tags: true
    repo: grissius/sheep-a-changelog
